### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by farodin91**

### CODE REVIEW

**Comment by farodin91** [comment]
You have to develop github actions as branch of the repo.

**Comment by farodin91** [comment]
We could also add a standard style checker for example editorconfig.

**Review by porunov — APPROVED** [review]
Great work! LGTM.

**Review by FlorianHockmann — APPROVED** [review]
I briefly skimmed over the changes and they look good to me. I don't think that I need to review this thoroughly if you two (@farodin91 and @porunov) think that it's good.
But maybe someone who has worked on the FoundationDB adapter could review this, like @rngcntr?

**Comment by rngcntr** [comment]
I'm unfamiliar with GitHub actions and it's config files but I took a quick look at the source code to ensure that no functional changes were introduced

**Review by rngcntr — APPROVED** [review]

**Pull request merged**
